POST https://humble-space-computing-machine-q7pxjppw65xph46jp-8080.app.github.dev/producto/marca/1001/nuevo
Content-Type: application/json

{
 "nombre":"TU NOMBRE",
"descripcion": "TU NOMBRE COMPLETO",
	"precio":600,
	"stock":3
}

### Ajustar stock
POST https://humble-space-computing-machine-q7pxjppw65xph46jp-8080.app.github.dev/producto/stock/ajuste
Content-Type: application/json

{
  "idProducto": 1014,
  "stock": 4
}

### Consultar producto por id
GET https://humble-space-computing-machine-q7pxjppw65xph46jp-8080.app.github.dev/producto/1014


### Registrar pedido
POST https://verbose-chainsaw-x55597q54wqjh9vg-8080.app.github.dev/pedido/nuevo
Content-Type: application/json

{
 "items":[
   {
     "idProducto": 1014,
     "cantidad": 4,
     "precioUnitario":3000
   }
 ]
}



